### ISSUE TITLE
Unable to open chrome after run

### ISSUE THREAD

**Issue by itsdeepceh** [netsquare/BrowserBruter#2] opened 2024-04-08 11:54 UTC
Hello Team,

I would like to thank you for a great tool, unfortunately i am facing an issue that after successful run its unable to open chrome browser for testing itself,

highly appreciated your help on this

**Comment by zinja-coder** [comment] 2024-04-09 08:06
Hey there, thanks for reaching us out. Technically this should never have happened as the tool uses it's own browser binary. It does not interact with your system's chrome browser. May you please share more details regarding this issue. We really want to help you but we need some details.

Kindly provide following if possible - 
1. Is there any exceptions?
2. May please any Screenshots or video if possible.
3. What was the command you used to run this tool?

Thanks for reaching.

**Comment by zinja-coder** [comment] 2024-04-09 08:48
> Hello Team,
> 
> I would like to thank you for a great tool, unfortunately i am facing an issue that after successful run its unable to open chrome browser for testing itself,
> 
> highly appreciated your help on this

Also keep note that it requires internet connection at startup. Without good internet connection, it won't start the browser.

**Comment by masterc123** [comment] 2024-04-10 03:45
I'm experiencing a similar issue where Chrome doesn't open when I run a command.

1. Are there any exceptions or error messages?
   - No, there aren't any exceptions or error messages.

2. Can you provide screenshots or a video of the issue?
   - Unfortunately, I can't provide screenshots, but the output message prompts me to press Enter to pause the attack. However, it doesn't display any progress and just stops there.

3. What command did you use to run this tool?
   - command prompt (cmd).

**Comment by zinja-coder** [comment] 2024-04-10 05:09
> I'm experiencing a similar issue where Chrome doesn't open when I run a command.
> 
> 1. Are there any exceptions or error messages?
>    - No, there aren't any exceptions or error messages.
> 
> 2. Can you provide screenshots or a video of the issue?
>    - Unfortunately, I can't provide screenshots, but the output message prompts me to press Enter to pause the attack. However, it doesn't display any progress and just stops there.
> 
> 3. What command did you use to run this tool?
>    - command prompt (cmd).

Hey thanks for sharing. You are using cmd. That means you are using windows. This tool as of now does not have support for windows.

**Comment by itsdeepceh** [comment] 2024-04-10 09:06
Dear Netsquare/Browserbruter

I have found solution if chrome is already installed then it won’t work,
you need to remove it completely from your system

And install using requirement file again

Let me know if this help you

**Comment by zinja-coder** [comment] 2024-04-10 09:11
Hey @itsdeepceh thanks for the update. It's strange actually. May you kindly provide us which platform you are on. Because BrowserBruter has its own chrome in 'res/' directory. It should never interfere with your systems chrome. 

Anyways, Glad you were able to solve it. I hope you have found the tool useful. Let us know if you are required any further assistance.

**Comment by zinja-coder** [comment] 2024-04-21 14:23
Hey @itsdeepceh may you please provide update. Else I have to mark this as closed.

**Comment by itsdeepceh** [comment] 2024-04-22 06:09
Dear

Its working for me now, thank you for your quick response

**Comment by zinja-coder** [comment] 2024-04-22 06:57
Closing this as the issue is resolved.

**Closed as completed** 2024-04-22 06:58 UTC
Labels: bug
